name: ElastixPublish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-2022]
        include:
          - os: ubuntu-22.04
            cuda_toolkit_version: '12.8.0'
            libtorch-cuda-url: "https://download.pytorch.org/libtorch/cu128/libtorch-shared-with-deps-2.8.0%2Bcu128.zip"
            itk-git-tag: "v5.4.1"
            cuda-version: "cu128"
            c-compiler: "gcc"
            cxx-compiler: "g++"
            cmake-build-type: "Release"
            libs:
              - elastix-build/bin/libelxANNlib.so
              - elastix-build/bin/libelxANNlib
          - os: windows-2022
            cuda_toolkit_version: '12.8.0'
            libtorch-cuda-url: "https://download.pytorch.org/libtorch/cu128/libtorch-win-shared-with-deps-2.8.0%2Bcu128.zip"
            itk-git-tag: "v5.4.1"
            cuda-version: "cu128"
            c-compiler: "cl.exe"
            cxx-compiler: "cl.exe"
            cmake-build-type: "Release"
            libs:
              - elastix-build/bin/elxANNlib.dll
            vcvars64: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
    steps:
      - name: Free disk space
        if: matrix.os != 'windows-2022'
        run: |
          echo "Disk before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet \ /usr/local/lib/android \ /opt/ghc \ /opt/hostedtoolcache
          sudo docker system prune -af || true
          sudo rm -rf /var/lib/apt/lists/*
          echo "Disk after cleanup:"
          df -h
        shell: bash

      - name: Clone elastix
        uses: actions/checkout@v3

      - name: Make directory structure
        run: |
          items=(*)
          mkdir elastix-source
          mv ${items[*]} elastix-source
          mv .editorconfig elastix-source
          mv .clang-format elastix-source
          mv elastix-source/Dockerfile .
        shell: bash

      - name: Download and extract libtorch
        uses: ./.github/actions/download_libtorch
        with:
          libtorch_url: ${{ matrix.libtorch-cuda-url }}

      - name: Clone and build ITK
        uses: ./.github/actions/build_itk
        with:
          itk-git-tag: ${{ matrix.itk-git-tag }}
          c-compiler: ${{ matrix.c-compiler }}
          cxx-compiler: ${{ matrix.cxx-compiler }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          vcvars: ${{ matrix.vcvars64 }}

      - name: Install CUDA Toolkit (Windows)
        if: matrix.os == 'windows-2022'
        uses: Jimver/cuda-toolkit@v0.2.29
        with:
          cuda: 11.8.0
          use-github-cache: false
          use-local-cache: false

      - name: Install CUDA Toolkit (Linux)
        if: matrix.os != 'windows-2022'
        uses: Jimver/cuda-toolkit@v0.2.23
        with:
          cuda: 12.8.0
          sub-packages: '["toolkit"]'
          method: 'network'

      - name: Get specific version of CMake, Ninja
        uses: lukka/get-cmake@latest

      - name: Build elastix
        uses: ./.github/actions/build_elastix
        with:
          c-compiler: ${{ matrix.c-compiler }}
          cxx-compiler: ${{ matrix.cxx-compiler }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          vcvars: ${{ matrix.vcvars64 }}

      - name: Publish
        uses: ./.github/actions/publish
        with:
          libs: ${{ join(matrix.libs, ' ') }}
          upload-name: ${{ matrix.os }}-libtorch-2.8.0-${{ matrix.cuda-version }}
          docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}