name: ElastixPublish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
        include:
          - os: ubuntu-22.04
            libtorch-cpu-url: "https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.8.0%2Bcpu.zip"
            libtorch-cuda-url: "https://download.pytorch.org/libtorch/cu128/libtorch-shared-with-deps-2.8.0%2Bcu128.zip"
            cuda_toolkit_version: '12.8.0'
            itk-git-tag: "v5.4.5"
            c-compiler: "gcc"
            cxx-compiler: "g++"
            cmake-build-type: "Release"
            libs:
              - elastix-build/bin/libelxANNlib.so
              - elastix-build/bin/libelxANNlib.so.1
          - os: windows-2022
            libtorch-cpu-url: "https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-2.8.0%2Bcpu.zip"
            libtorch-cuda-url: "https://download.pytorch.org/libtorch/cu128/libtorch-win-shared-with-deps-2.8.0%2Bcu128.zip"
            cuda_toolkit_version: '12.8.0'
            itk-git-tag: "v5.4.5"
            c-compiler: "cl.exe"
            cxx-compiler: "cl.exe"
            cmake-build-type: "Release"
            libs:
              - elastix-build/bin/elxANNlib.dll
            vcvars64: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          - os: macos-14
            c-compiler: "clang"
            cxx-compiler: "clang++"
            libtorch-cpu-url: "https://download.pytorch.org/libtorch/cpu/libtorch-macos-arm64-2.8.0.zip"
            itk-git-tag: "v5.4.5"
            cmake-build-type: "Release"
            libs:
              - elastix-build/bin/libelxANNlib.1.dylib
              - elastix-build/bin/libelxANNlib.dylib
    steps:
      - name: Free disk space
        if: matrix.os != 'windows-2022'
        run: |
          echo "Disk before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
          sudo docker system prune -af || true
          sudo rm -rf /var/lib/apt/lists/*
          echo "Disk after cleanup:"
          df -h
        shell: bash

      - name: Clone elastix
        uses: actions/checkout@v3

      - name: Make directory structure
        run: |
          items=(*)
          mkdir elastix-source
          mv ${items[*]} elastix-source
          mv .editorconfig elastix-source
          mv .clang-format elastix-source
          mv elastix-source/Dockerfile .
        shell: bash

      - name: Get specific version of CMake, Ninja
        uses: lukka/get-cmake@latest

      - name: Clone and build ITK
        uses: ./.github/actions/build_itk
        with:
          itk-git-tag: ${{ matrix.itk-git-tag }}
          c-compiler: ${{ matrix.c-compiler }}
          cxx-compiler: ${{ matrix.cxx-compiler }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          vcvars: ${{ matrix.vcvars64 }}

      - name: Download and extract libtorch cpu (non-MacOS)
        if: matrix.os != 'macos-14'
        uses: ./.github/actions/download_libtorch
        with:
          libtorch_url: ${{ matrix.libtorch-cpu-url }}

      - name: Build libtorch cpu (MacOS)
        if: matrix.os == 'macos-14'
        uses: ./.github/actions/build_libtorch
        with:
          install_prefix: ${{ github.workspace }}/libtorch/libtorch

      - name: Configure/Build elastix with IMPACT libtorch cpu
        uses: ./.github/actions/build_elastix
        with:
          c-compiler: ${{ matrix.c-compiler }}
          cxx-compiler: ${{ matrix.cxx-compiler }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          vcvars: ${{ matrix.vcvars64 }}

      - name: Cleanup libtorch (CPU) (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mv elastix-build/bin/libImpactMetric.so elastix-build/bin/libImpactMetricCpu.so
          rm -rf libtorch
        shell: bash

      - name: Cleanup libtorch (CPU) [Windows]
        if: matrix.os == 'windows-2022'
        run: |
          mv elastix-build/bin/ImpactMetric.dll elastix-build/bin/ImpactMetricCpu.dll
          rmdir /S /Q libtorch
        shell: cmd

      - name: Install CUDA Toolkit (Windows)
        if: matrix.os == 'windows-2022'
        uses: Jimver/cuda-toolkit@v0.2.29
        with:
          cuda: 11.8.0
          use-github-cache: false
          use-local-cache: false

      - name: Install CUDA Toolkit (Linux)
        if: matrix.os == 'ubuntu-22.04'
        uses: Jimver/cuda-toolkit@v0.2.23
        with:
          cuda: 12.8.0
          sub-packages: '["toolkit"]'
          method: 'network'

      - name: Download and extract libtorch cuda
        if: matrix.os != 'macos-14'
        uses: ./.github/actions/download_libtorch
        with:
          libtorch_url: ${{ matrix.libtorch-cuda-url }}

      - name: Build elastix with Impact Cuda (Windows)
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          cd elastix-build
          cmake -DCMAKE_C_COMPILER="${{ inputs.c-compiler }}" ^
              -DCMAKE_CXX_COMPILER="${{ inputs.cxx-compiler }}" ^
              -DCMAKE_BUILD_TYPE="${{ inputs.cmake-build-type }}" ^
              -DITK_DIR=../ITK-build ^
              -DCMAKE_CUDA_FLAGS="-allow-unsupported-compiler -Xcompiler \"/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH\"" ^
              -DTorch_DIR=../libtorch/libtorch/share/cmake/Torch ^
              -DUSE_ALL_COMPONENTS=ON ^
              -DBUILD_TESTING:BOOL=ON ^
              -DELASTIX_USE_GTEST=ON ^
              -GNinja ../elastix-source
          cmake --build . --target ImpactMetric
          mv bin/ImpactMetric.dll bin/ImpactMetricCuda.dll
          mv bin/ImpactMetricCpu.dll bin/ImpactMetric.dll


      - name: Build elastix with Impact Cuda (Linux)
        if: matrix.os == 'ubuntu-22.04'
        shell: bash
        run: |
          cd elastix-build
          cmake -DCMAKE_C_COMPILER="${{ inputs.c-compiler }}" \
              -DCMAKE_CXX_COMPILER="${{ inputs.cxx-compiler }}" \
              -DCMAKE_BUILD_TYPE="${{ inputs.cmake-build-type }}" \
              -DITK_DIR=../ITK-build \
              -DTorch_DIR=../libtorch/libtorch/share/cmake/Torch \
              -DUSE_ALL_COMPONENTS=ON \
              -DBUILD_TESTING:BOOL=ON \
              -DELASTIX_USE_GTEST=ON \
              -GNinja ../elastix-source
          cmake --build . --target ImpactMetric
          mv bin/libImpactMetric.so bin/libImpactMetricCuda.so
          mv bin/libImpactMetricCpu.so bin/libImpactMetric.so


      - name: Publish
        uses: ./.github/actions/publish
        with:
          libs: ${{ join(matrix.libs, ' ') }} elastix-build/bin/*ImpactMetric*
          upload-name: ${{ matrix.os }}-libtorch-2.8.0
          docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
